### ISSUE TITLE
Two related papers

### ISSUE THREAD

**Issue by williamyang1991** [AlonzoLeeeooo/awesome-video-generation#7]
I found my two papers are related but unfortunately not summaized in this project.

https://github.com/williamyang1991/Rerender_A_Video
https://github.com/williamyang1991/FRESCO

**Comment by AlonzoLeeeooo** [comment]
Hi @williamyang1991 ,

Thanks for your precious information! The papers and their corresponding resources are updated in [this commit](https://github.com/AlonzoLeeeooo/awesome-video-generation/commit/578fff2217aad6865ff5b75448baa8d329779ff1).

**Comment by williamyang1991** [comment]
Thank you!
